verbose_all: True

data_config:
  data_file: /global/common/software/desi/users/mlokken/cupix/data/px_measurements/forecast/fcast_best_fit_arinyo_from_p1d_real_bf3_binned_out_px-zbins_4-thetabins_10_w_res_noiseless.hdf5
  verbose:
  kM_max_cut_AA: 1
  km_max_cut_AA: 1.2
  theta_min_cut_arcmin:

cosmo_config:
  H0: 67.66
  mnu: 0.0
  ombh2: 0.02242
  omch2: 0.11933
  omk: 0.0
  omnuh2: 0.0
  w: -1.0
  wa: 0.0

theory_config:
  verbose:
  iz: 0
  default_lya_model: best_fit_arinyo_from_p1d
  include_sky:
  include_hcd:
  include_metal:
  include_continuum:

  # fill parameters for EITHER igm_config OR lya_config
  # which params are filled should be consistent with default_lya_model.
  igm_config:
    Delta2_p: 
    n_p:
    mF:
    gamma:
    sigT_Mpc:
    kF_Mpc:

  lya_config:
    bias: -0.1173
    beta: 1.416102
    q1: 0.259185
    kp_Mpc: 10.41077
    kv_Mpc: 0.24245
    av: 0.43190
    bv: 1.67688
    q2: 0.271033

  contaminant_config:
    # hcd params:
    b_H:
    beta_H:
    L_H_Mpc:
    # metal params:
    b_X:
    beta_X:
    # sky params:
    b_noise_Mpc:
    # continuum params:
    kC_Mpc:
    pC:

likelihood_config:
  verbose:
  N_theta_average: 1
