verbose_all: True

posterior_config:
  verbose: False
  fixed_params:

minimizer_config:
  verbose:


sampler_config:
  # set these only if you want to change the defaults
  verbose:
  nwalkers:
  max_nsteps:
  nburnin:

params_config:
  bias:
    min_value:
    max_value:
    ini_value:
    true_value:
    gauss_prior_mean:
    gauss_prior_width:
    delta:
  beta:
    min_value:
    max_value:
    ini_value:
    true_value:
    gauss_prior_mean:
    gauss_prior_width:
    delta:
  q1:
    min_value:
    max_value:
    ini_value:
    true_value:
    gauss_prior_mean:
    gauss_prior_width:
    delta:
  bv:
    min_value:
    max_value:
    ini_value:
    true_value:
    gauss_prior_mean:
    gauss_prior_width:
    delta:
  av:
    min_value:
    max_value:
    ini_value:
    true_value:
    gauss_prior_mean:
    gauss_prior_width:
    delta: